### ISSUE TITLE
Queries show up as fields. Is this suppose to happen?

### ISSUE THREAD

**Issue by rterysen** [jakepusateri/graphql-list-fields#11]
```
query{
  Viewer{
 		email
     User(_id:"b21fcf2d-801f-43fb-b203-7ff047001ba6"){
      first_name
    }
  }
}
```
Should "User" show up in the `select` array below?
`const select = getFieldNames(info);`

If it is not suppose to. Do you know what I could change to make this not happen?

**Comment by jakepusateri** [comment]
In your example, `User` is a field. It is a field that has an argument of `id`, but still a field. This behavior is intentional.
