### ISSUE TITLE
parameter for how many levels for nesting we want

### ISSUE THREAD

**Issue by capaj** [jakepusateri/graphql-list-fields#14]
currently I get all the fields that are nested from this level down.
For example I get this output on `getFieldNames(info)`:
```
info:  [ 'email', 'organisation.id', 'organisation.name' ]
```
If I could specify `getFieldNames(info, 1)` and get:
```
info:  [ 'email' ]
```

That'd be great. :stuck_out_tongue_closed_eyes:

**Comment by WNemencha** [comment]
Just do something like this?

```js
const allFields = getFieldNames(info)
const firstLevelFields = allFields.filter(f => f.indexOf('.') === 0)
const secondLevelFields = allFields.filter(f => f.indexOf('.') === 1)
// etc...
```
