### ISSUE TITLE
Suggestion to improve this module with ready to use parameters.

### ISSUE THREAD

**Issue by ProphetDaniel** [jakepusateri/graphql-list-fields#16]
I was thinking about this module, and I think I can contribute so that this can also be used right away as GraphQL parameters.

Instead the result from:
`[ 'id', 'name', 'referral.user.id', 'referral.rate' ]`
becomes:
`id name referral{user{id} rate}`

Here is the code used to transform.
```
import getFieldNames from 'graphql-list-fields';
import merge from 'deepmerge';

const unflatten = arrays => {
  let obj = {}
  if (arrays.length <= 1) {
    obj[arrays[0]] = {};
    return obj;
  }
  obj[arrays[0]] = unflatten(arrays.slice(1));
  return obj;
}
const getFormattedFieldNames = info => {
  const fieldsMap = getFieldNames(info).map(field => field.split('.'));
  const unFlat = fieldsMap.map(arr => unflatten(arr));
  const merged = merge.all(unFlat);
  const result = JSON.stringify(merged).replace(/"|:|{}/g,'').replace(/,/g, ' ').slice(1,-1);
  
  return result;
}

export { getFormattedFieldNames };
```

**Comment by jakepusateri** [comment]
Interesting idea. I can see this being useful for people who delegate subsections of their schema to other servers, but it doesn't fit with the scope of this module. You're welcome to publish a new module that wraps this one with that output format though.
