### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MatthiasKunnen** [jakepusateri/graphql-list-fields#9]
This repository doesn't have a `LICENSE` file. This means that everyone that uses it is committing copyright infringement. Will a license be added?

**Comment by jakepusateri** [comment]
The license is pretty clearly listed as MIT in the package.json file

**Comment by MatthiasKunnen** [comment]
I must have looked over it. Nevertheless, I would still recommend adding a license file to the repo as per GitHubs recommendations.
